export const SET_REVIEWS = 'SET_REVIEWS';
export const SET_REVIEWS_SEARCH_PARAM = 'SET_REVIEWS_SEARCH_PARAM';
export const RESET_REVIEWS_SEARCH_PARAM = 'RESET_REVIEWS_SEARCH_PARAM';
export const CLICK_SORT = 'CLICK_SORT';
export const APPLY_TEXT_FILTER = 'APPLY_TEXT_FILTER';
